### ISSUE TITLE
Gestion de la précédence des opérateurs en recherche multicritères

### ISSUE THREAD

**Issue by n1k0** [ln-nicolas/api_insee#3]
Hello,

Super taf sur l'API, vraiment. Un petit retour concernant la gestion de la précédence des opérateurs de recherche `AND` et `OR` sur le multicritères ; si j'essaye d'effectuer cette recherche :

```python
q = Field("codePostalEtablissement", "34830")
q = q & (
    Field("denominationUniteLegale", f'"bistro brooklyn"~')
    | Field("nomUniteLegale", f'"bistro brooklyn"~')
    | Periodic(Field("denominationUsuelleEtablissement", f'"bistro brooklyn"~'))
)
api.siret(q=q)
print(request.url)
```

L'URL de requête générée est celle ci :

```
...?q=codePostalEtablissement:34830 AND denominationUniteLegale:"bistro brooklyn"~ OR nomUniteLegale:"bistro brooklyn"~ OR periode(denominationUsuelleEtablissement:"bistro brooklyn"~)
```

Qui renvoit un message d'erreur `400` (formattage de la requête multicritère `q` incorrect). Je pense que c'est lié à l'absence d'explicitation de la précédence des opérateurs `AND` et `OR`.

En effet, en exécutant manuellement la requête en positionnant les parenthèses qui lèvent lambiguité, ça fonctionne :

```
...?q=codePostalEtablissement:34830 AND (denominationUniteLegale:"bistro brooklyn"~ OR nomUniteLegale:"bistro brooklyn"~ OR periode(denominationUsuelleEtablissement:"bistro brooklyn"~))
```

Là ça me renvoit bien un résultat avec l'établissement qui va bien.

Merci d'avance pour ton aide !

**Comment by n1k0** [comment]
Pour info j'ai pu régler le souci en créant mon propre *criteria* :

```python
class OrGroup(criteria.Base):
    def __init__(self, *criteria, **kwargs):
        self.criteria_list = criteria

    def toURLParams(self):
        inner = " OR ".join([ct.toURLParams() for ct in self.criteria_list])
        return f"({inner})"
```

Ce qui donne à l'usage :

```python
q = Field("codePostalEtablissement", "34830") & OrGroup(
    Field("denominationUniteLegale", f'"bistro brooklyn"~'),
    Field("nomUniteLegale", f'"bistro brooklyn"~'),
    Periodic(Field("denominationUsuelleEtablissement", f'"bistro brooklyn"~')),
)
```

Dispo pour créer une PR si cela suscite un quelconque intérêt.

**Comment by ln-nicolas** [comment]
Hello ! 

Merci pour l'interêt porter à ce projet. Je suis vraiment désolé de répondre aussi tardivement :( 
N'hésites pas à faire une PR si tu le souhaites 👍 

Juste par curiosité, dans quel cadre es tu amené à utiliser l'api ?

**Comment by n1k0** [comment]
> Juste par curiosité, dans quel cadre es tu amené à utiliser l'api ?

Dans le cadre du projet [Acceslibre](https://acceslibre.beta.gouv.fr/), plus particulièrement sur la [recherche d'établissements](https://github.com/MTES-MCT/acceslibre/blob/master/erp/sirene.py#L228-L251) :)
