### ISSUE TITLE
support BDM

### ISSUE THREAD

**Issue by mxdev88** [ln-nicolas/api_insee#4]
hello @ln-nicolas, do you have any plans to support BDM within this library? I'm looking to get series data from INSEE. thanks

**Comment by ln-nicolas** [comment]
Hello @mxdev88 what do you mean by DBM ?

**Comment by mxdev88** [comment]
The lib supports siret and sirene API endpoints from the Sirene API. INSEE offers 3 other APIs in their [catalog](https://api.insee.fr/catalogue/).
I'm interested to interact with the [BDM](https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/item-info.jag?name=BDM&version=V1&provider=insee) one.
(Sorry I mispelled in my original post, I meant BDM. I've corrected).

**Comment by mxdev88** [comment]
The lib supports siret and sirene API endpoints from the Sirene API. INSEE offers 3 other APIs in their [catalog](https://api.insee.fr/catalogue/).
I'm interested to interact with the [BDM](https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/item-info.jag?name=BDM&version=V1&provider=insee) one.
(Sorry I mispelled in my original post, I meant BDM. I've corrected).

**Comment by ln-nicolas** [comment]
It's a great idea, but I don't plan to support this endpoint for the while. Fell free to create a pull-request :)

**Comment by mxdev88** [comment]
After looking into it further, I may be able to use one of these alternatives: [sdmx1](https://sdmx1.readthedocs.io/en/latest/index.html) or [pandasdmx](https://pandasdmx.readthedocs.io/en/v1.0/index.html).
