### ISSUE TITLE
Bad request URl

### ISSUE THREAD

**Issue by RomainTT** [ln-nicolas/api_insee#6]
Bonjour,

J’ai essayé la lib aujourd’hui (**version 1.5**), et en exécutant les exemples du README, j’obtiens une erreur :

```
>>> data = api.siren(q={
    ...:     'codeCommuneEtablissement' : 92046,
    ...:     'unitePurgeeUniteLegale' : True
    ...: }).get()
…
# traceback
…
RequestExeption: bad request url : https://api.insee.fr/entreprises/sirene/V3/siren?q=codeCommuneEtablissement:92046 AND unitePurgeeUniteLegale:True

```

En revanche la requête suivante fonctionne par exemple (toujours depuis le README) : 

```
data = api.siren('005520135', date='2018-01-01').get()
```

**Comment by caroheymes** [comment]
Bonjour, Même problème que Romain
`RequestExeption: bad request url : https://api.insee.fr/entreprises/sirene/V3/siren?q=codeCommuneEtablissement:60003 AND unitePurgeeUniteLegale:Tr`

**Comment by FlavienRx** [comment]
Bonjour @RomainTT @caroheymes si ce n'est pas trop tard et que cela peut vous aider, la requête exemple fonctionne pour le `siret`. Même sur `api.insee.fr` dans la console API, la requête sur le end point `siret` fonctionne mais pas pour le end point `siren`.
