### ISSUE TITLE
Deprecated URLs

### ISSUE THREAD

**Issue by ironsilk** [ln-nicolas/api_insee#9]
Hey there,

First of all thanks for the library it works very well and it's really easy to use. 

As you know they've deprecated the old endpoints, i see you've addressed this in commit: https://github.com/ln-nicolas/api_insee/commit/b98752aa7205d1e406a16a3b6a4c26f02eae9f1f .

I wanted to maybe suggest dropping the `V3.11` since it would also work as such:  `'/entreprises/sirene/siren'` instead of `'/entreprises/sirene/V3.11/siren'` and it might be easier to maintain.

Secondly, are you planning to release these changes? The config.py is not exposed through the __init__ so there's no easy way of changing the configuration of the library from the script we're importing it.

Thanks!

**Comment by gautierrog** [comment]
Great ideas, dropping the version in URL is more future proof et we would need a release for url update as well.

**Comment by QualiDieu** [comment]
Is it possible to release 1.6 with this fix ?

**Comment by ln-nicolas** [comment]
A new version has been release 
Sorry for the long delay
